city_to_country = {
    'Crailsheim': 'Germany',
    'Dortmund': 'Germany',
    'Stuttgart': 'Germany',
    'München': 'Germany',
    'Berlin': 'Germany',
    'Wien': 'Austria',
    'Offenbach am Main': 'Germany',
    'Eberbach': 'Germany',
    'Görlitz': 'Germany',
    'Pfedelbach': 'Germany',
    'Unterhaching': 'Germany',
    'Rüdesheim am Rhein': 'Germany',
    'Dresden': 'Germany',
    'Gummersbach': 'Germany',
    'Kassel': 'Germany',
    'Wenzenbach': 'Germany',
    'Merseburg': 'Germany',
    'Gommern': 'Germany',
    'Pommelsbrunn': 'Germany',
    'Duisburg': 'Germany',
    'Herzogenrath': 'Germany',
    'Schwandorf': 'Germany',
    'Mainz': 'Germany',
    'Podskalie': 'Slovakia',
    'Zinnowitz': 'Germany',
    'Quedlinburg': 'Germany',
    'Wolfsburg': 'Germany',
    'Weilburg': 'Germany',
    'Dillenburg': 'Germany',
    'Neu-Ulm': 'Germany',
    'Lauter-Bernsbach': 'Germany',
    'Bonn': 'Germany',
    'Riedstadt': 'Germany',
    'Rosenheim': 'Germany',
    'Mönchengladbach': 'Germany',
    'Neuburg': 'Germany',
    'Rostock': 'Germany',
    'Bad Oeynhausen': 'Germany',
    'Chemnitz': 'Germany',
    'Diez': 'Germany',
    'Nürnberg': 'Germany',
    'Laubach': 'Germany',
    'Düren': 'Germany',
    'Düsseldorf': 'Germany',
    'Zwickau': 'Germany',
    'Bremen': 'Germany',
    'Halle': 'Germany',
    'Erbach': 'Germany',
    'Jünkerath': 'Germany',
    'Magdeburg': 'Germany',
    'Celle': 'Germany',
    'Germering': 'Germany',
    'Kleve': 'Germany',
    'Leinfelden-Echterdingen': 'Germany',
    'Garmisch-Partenkirchen': 'Germany',
    'Leipzig': 'Germany',
    'Hof': 'Germany',
    'Lünen': 'Germany',
    'Murr': 'Germany',
    'Bochum': 'Germany',
    'Leonberg': 'Germany',
    'Bad Homburg vor der Höhe': 'Germany',
    'Kiel': 'Germany',
    'Theres': 'Germany',
    'Lüchow': 'Germany',
    'Stolberg': 'Germany',
    'Bautzen': 'Germany',
    'Weiden': 'Germany',
    'Osterode am Harz': 'Germany',
    'Göppingen': 'Germany',
    'Ansbach': 'Germany',
    'Aachen': 'Germany',
    'Menden': 'Germany',
    'Iserlohn': 'Germany',
    'Aying': 'Germany',
    'Mannheim': 'Germany',
    'Hamburg': 'Germany',
    'Einhausen': 'Germany',
    'Minden': 'Germany',
    'Igalo': 'Montenegro',
    'Süßen': 'Germany',
    'Flensburg': 'Germany',
    'Tönning': 'Germany',
    'Aschaffenburg': 'Germany',
    'Holzwickede': 'Germany',
    'Villingen‑Schwenningen': 'Germany',
    'Ochtrup': 'Germany',
    'Klosterlechfeld': 'Germany',
    'Straubing': 'Germany',
    'Augsburg': 'Germany',
    'Rheine': 'Germany',
    'Singen': 'Germany',
    'Werl': 'Germany',
    'Schweinfurt': 'Germany',
    'Ditzingen': 'Germany',
    'Frankfurt': 'Germany',
    'Waldbronn': 'Germany',
    'Bad Wildbad im Schwarzwald': 'Germany',
    'Essen': 'Germany',
    'Weil am Rhein': 'Germany',
    'Lahnstein': 'Germany',
    'Osnabrück': 'Germany',
    'Lierschied': 'Germany',
    'Eggenfelden': 'Germany',
    'Trebgast': 'Germany',
    'Verl': 'Germany',
    'Wesel': 'Germany',
    'Frammersbach': 'Germany',
    'Grevesmühlen': 'Germany',
    'Perleberg': 'Germany',
    'Michelfeld': 'Germany',
    'Stralsund': 'Germany',
    'Zeitz': 'Germany',
    'Novi Sad': 'Serbia',
    'Münster': 'Germany',
    'Helmstedt': 'Germany',
    'Krefeld': 'Germany',
    'Rastatt': 'Germany',
    'Detmold': 'Germany',
    'Weinstadt': 'Germany',
    'Friedrichshafen': 'Germany',
    'Wächtersbach': 'Germany',
    'Weißenburg in Bayern': 'Germany',
    'Solingen': 'Germany',
    'Worms': 'Germany',
    'Schlangen': 'Germany',
    'Schwarzenberg': 'Germany',
    'Ludwigsburg': 'Germany',
    'Büchen': 'Germany',
    'Remscheid': 'Germany',
    'Kulmbach': 'Germany',
    'Burghausen': 'Germany',
    'Meinerzhagen': 'Germany',
    'Torgau': 'Germany',
    'Coesfeld': 'Germany',
    'Hartmannsdorf': 'Germany',
    'Adelschlag': 'Germany',
    'Eisenberg': 'Germany',
    'Kehl': 'Germany',
    'Delbrück': 'Germany',
    'Kempten': 'Germany',
    'Marburg': 'Germany',
    'Oranienburg': 'Germany',
    'Siegen': 'Germany',
    'Castrop-Rauxel': 'Germany',
    'Kalkar': 'Germany',
    'Würzburg': 'Germany',
    'Molsberg': 'Germany',
    'Rust': 'Germany',
    'Bad Hersfeld': 'Germany',
    'Südlohn': 'Germany',
    'Erfurt': 'Germany',
    'Wiesenttal': 'Germany',
    'Altenstadt': 'Germany',
    'Sankt Leon-Rot': 'Germany',
    'Friedrichsdorf': 'Germany',
    'Heinsberg': 'Germany',
    'Passau': 'Germany',
    'Darmstadt': 'Germany',
    'Ruhla': 'Germany',
    'Bad Nauheim': 'Germany',
    'Bärnau': 'Germany',
    'Erftstadt': 'Germany',
    'Arnsberg': 'Germany',
    'Pullach im Isartal': 'Germany',
    'Gelnhausen': 'Germany',
    'Liederbach am Taunus': 'Germany',
    'Gröditz': 'Germany',
    'Trier': 'Germany',
    'Buxtehude': 'Germany',
    'Uelzen': 'Germany',
    'Aldenhoven': 'Germany',
    'Lutherstadt Wittenberg': 'Germany',
    'Friedenweiler': 'Germany',
    'Witzeeze': 'Germany',
    'Neuss': 'Germany',
    'Pforzheim': 'Germany',
    'Königswinter': 'Germany',
    'Northeim': 'Germany',
    'Rohrdorf': 'Germany',
    'Filderstadt': 'Germany',
    'Übelbach': 'Austria',
    'Fürth': 'Germany',
    'Kerpen': 'Germany',
    'Warszawa': 'Poland',
    'Markdorf': 'Germany',
    'Piatek': 'Poland',
    'Hannover': 'Germany',
    'Mülheim an der Ruhr': 'Germany',
    'Erkner': 'Germany',
    'Monschau': 'Germany',
    'Bad Segeberg': 'Germany',
    'Lauf an der Pegnitz': 'Germany',
    'Oberasbach': 'Germany',
    'Naumburg': 'Germany',
    'Wandlitz': 'Germany',
    'Witten': 'Germany',
    'Obernheim': 'Germany',
    'Wilhelmshaven': 'Germany',
    'Heimbuchenthal': 'Germany',
    'Weiterstadt': 'Germany',
    'Braunfels': 'Germany',
    'Salzwedel': 'Germany',
    'Rechitsa': 'Belarus',
    'Freiburg': 'Germany',
    'Regensburg': 'Germany',
    'Leer': 'Germany',
    'Höhenkirchen-Siegertsbrunn': 'Germany',
    'Coburg': 'Germany',
    'Wolfenbüttel': 'Germany',
    'Niederorschel': 'Germany',
    'Vierden': 'Germany',
    'Ostbevern': 'Germany',
    'Bad Pyrmont': 'Germany',
    'Stelle': 'Germany',
    'Wadgassen': 'Germany',
    'Leingarten': 'Germany',
    'Obermarchtal': 'Germany',
    'Güglingen': 'Germany',
    'Linz': 'Austria',
    'Sankt Ingbert': 'Germany',
    'Staufen im Breisgau': 'Germany',
    'Baku': 'Azerbaijan',
    'Erlensee': 'Germany',
    'Erkrath': 'Germany',
    'Kornwestheim': 'Germany',
    'Wiesbaden': 'Germany',
    'Leutershausen': 'Germany',
    'Rees': 'Germany',
    'Schwerin': 'Germany',
    'Słupsk': 'Poland',
    'Reutlingen': 'Germany',
    'Hamm': 'Germany',
    'Köln': 'Germany',
    'Gdańsk': 'Poland',
    'Allendorf': 'Germany',
    'Gladenbach': 'Germany',
    'Euskirchen': 'Germany',
    'Gerlingen': 'Germany',
    'Lübeck': 'Germany',
    'Büren': 'Germany',
    'Ganderkesee': 'Germany',
    'Ohrdruf': 'Germany',
    'Beverungen': 'Germany',
    'Oldenburg': 'Germany',
    'Usingen': 'Germany',
    'Geilenkirchen': 'Germany',
    'Leichlingen': 'Germany',
    'Veldenz': 'Germany',
    'Duschanbe': 'Tajikistan',
    'Ahad Al Masarihah': 'Yemen',
    'Werder': 'Germany',
    'Morsbach': 'Germany',
    'Herdecke': 'Germany',
    'Gießen': 'Germany',
    'Seevetal': 'Germany',
    'Korschenbroich': 'Germany',
    'Stendal': 'Germany',
    'Teublitz': 'Germany',
    'Meerbusch': 'Germany',
    'Obergünzburg': 'Germany',
    'Eggolsheim': 'Germany',
    'Limbach-Oberfrohna': 'Germany',
    'Kraichtal': 'Germany',
    'Rathenow': 'Germany',
    'Śrem': 'Poland',
    'Mülheim-Kärlich': 'Germany',
    'Babenhausen': 'Germany',
    'Heidenheim': 'Germany',
    'Rotterdam': 'Netherlands',
    'Cremlingen': 'Germany',
    'Hörstel': 'Germany',
    'Rinteln': 'Germany',
    'Gütersloh': 'Germany',
    'Röttingen': 'Germany',
    'Bayreuth': 'Germany',
    'Ajman': 'United Arab Emirates',
    'Hagen': 'Germany',
    'Rötgesbüttel': 'Germany',
    'Parchim': 'Germany',
    'Emsdetten': 'Germany',
    'Randersacker': 'Germany',
    'Erding': 'Germany',
    'Kressbronn am Bodensee': 'Germany',
    'Essing': 'Germany',
    'Nesselwang': 'Germany',
    'Braunschweig': 'Germany',
    'Zoetermeer': 'Netherlands',
    'Karlsfeld': 'Germany',
    'Nuenchritz': 'Germany',
    'Obergriesbach': 'Germany',
    'Karlsruhe': 'Germany',
    'Paderborn': 'Germany',
    'Remchingen': 'Germany',
    'Großrosseln': 'Germany',
    'Neuhemsbach': 'Germany',
    'Nebra (Unstrut)': 'Germany',
    'Herford': 'Germany',
    'Lubrza': 'Poland',
    'Kalanchak': 'Ukraine',
    'Piotrków Trybunalski': 'Poland',
    'Neumünster': 'Germany',
    'Hennef': 'Germany',
    'Wörthsee': 'Germany',
    'Monheim am Rhein': 'Germany',
    'Klasztorna': 'Poland',
    'Taraz': 'Kazakhstan',
    'Troisdorf': 'Germany',
    'Henstedt-Ulzburg': 'Germany',
    'Achberg': 'Germany',
    'Bialystok': 'Poland',
    'Königsmoos': 'Germany',
    'Warburg': 'Germany',
    'Stade': 'Germany',
    'Großbreitenbach': 'Germany',
    'Bad Driburg': 'Germany',
    'Sollstedt': 'Germany',
    'Esslingen am Neckar': 'Germany',
    'Cloppenburg': 'Germany',
    'Landshut': 'Germany',
    'Karstädt': 'Germany',
    'Steinfurt': 'Germany',
    'Tatabanya': 'Hungary',
    'Gerolstein': 'Germany',
    'Astana': 'Kazakhstan',
    'Dabrowa Gornicza': 'Poland',
    'Schwanewede': 'Germany',
    'Glendale': 'United States',
    'Hückelhoven': 'Germany',
    'Cheremkhovo': 'Russia',
    'Schwarzheide': 'Germany',
    'Böhlen': 'Germany',
    'Pleinfeld': 'Germany',
    'Hettenshausen': 'Germany',
    'Bünde': 'Germany',
    'Sankt Georgen im Schwarzwald': 'Germany',
    'Lichtenfels': 'Germany',
    'Fulda': 'Germany',
    'Riesa': 'Germany',
    'Löbau': 'Germany',
    'Waren': 'Germany',
    'Hameln': 'Germany',
    'Aichwald': 'Germany',
    'Eppelheim': 'Germany',
    'Bad Berleburg': 'Germany',
    'Aalen': 'Germany',
    'Minsk': 'Belarus',
    'Oberding': 'Germany',
    'Wermelskirchen': 'Germany',
    'Jindrichuv Hradec': 'Czech Republic',
    'Trossingen': 'Germany',
    'Stein': 'Germany',
    'Nizhny Novgorod': 'Russia',
    'Murom': 'Russia',
    'Bad Wörishofen': 'Germany',
    'Twistringen': 'Germany',
    'Langenselbold': 'Germany',
    'Alsfeld': 'Germany',
    'Limeshain': 'Germany',
    'Helmstidde': 'Germany',
    'Schwalbach': 'Germany',
    'Alfeld': 'Germany',
    'Mainz-Kastel': 'Germany',
    'Forchheim': 'Germany',
    'Altenkirchen': 'Germany',
    'Velden': 'Germany',
    'Alzenau in Unterfranken': 'Germany',
    'Bühl': 'Germany',
    'Bad Tölz': 'Germany',
    'Schkeuditz': 'Germany',
    'Poing': 'Germany',
    'Tuttlingen': 'Germany',
    'Semej': 'Kazakhstan',
    'Cuxhaven': 'Germany',
    'Kirchlauter': 'Germany',
    'Speyer': 'Germany',
    'Untersiemau': 'Germany',
    'Słubice': 'Poland',
    'Pfalzgrafenweiler': 'Germany',
    'Wetzlar': 'Germany',
    'Reichenau': 'Germany',
    'Scharbeutz': 'Germany',
    'Kirchheim': 'Germany',
    'Blankenfelde': 'Germany',
    'Güstrow': 'Germany',
    'Frechen': 'Germany',
    'Vechta': 'Germany',
    'Leuna': 'Germany',
    'Coswig': 'Germany',
    'Kisslegg': 'Germany',
    'Ebern': 'Germany',
    'Weilheim in Oberbayern': 'Germany',
    'Engen': 'Germany',
    'Lippstadt': 'Germany',
    'Konstanz': 'Germany',
    'Saarbrücken': 'Germany',
    'Aichach': 'Germany',
    'Heilbronn': 'Germany',
    'Sandersdorf': 'Germany',
    'Luckenwalde': 'Germany',
    'Inchenhofen': 'Germany',
    'Amberg': 'Germany',
    'Oberhausen': 'Germany',
    'Waiblingen': 'Germany',
    'Appen': 'Germany',
    'Chambon-sur-Lignon': 'France',
    'Nettetal': 'Germany',
    'Kirchlinteln': 'Germany',
    'Ottobrunn': 'Germany',
    'Koblenz': 'Germany',
    'Kusel': 'Germany',
    'Massenbachhausen': 'Germany',
    'Rangsdorf': 'Germany',
    'Hildesheim': 'Germany',
    'Heidelberg': 'Germany',
    'Senden': 'Germany',
    'Borna': 'Germany',
    'Bad Saulgau': 'Germany',
    'Cham': 'Germany',
    'Herne': 'Germany',
    'Lenningen': 'Germany',
    'Niederstetten': 'Germany',
    'Olpe': 'Germany',
    'Heinersreuth': 'Germany',
    'Speichersdorf': 'Germany',
    'Potsdam': 'Germany',
    'Bergisch Gladbach': 'Germany',
    'Weingarten': 'Germany',
    'Brandenburg an der Havel': 'Germany',
    'Lengerich': 'Germany',
    'Poppenhausen': 'Germany',
    'Villingen-Schwenningen': 'Germany',
    'Friesoythe': 'Germany',
    'Lingen': 'Germany',
    'Jena': 'Germany',
    'Griepswohld': 'Germany',
    'Garrel': 'Germany',
    'Herbrechtingen': 'Germany',
    'Binzen': 'Germany',
    'Friedberg': 'Germany',
    'Wuppertal': 'Germany',
    'Ulm': 'Germany',
    'Markgröningen': 'Germany',
    'Dinslaken': 'Germany',
    'Ravensburg': 'Germany',
    'Geyer': 'Germany',
    'Ilmenau': 'Germany',
    'Freital': 'Germany',
    'Engelsbrand': 'Germany',
    'Planegg': 'Germany',
    'Zwingenberg': 'Germany',
    'Abensberg': 'Germany',
    'Weinähr': 'Germany',
    'Wiefelstede': 'Germany',
    'Fritzlar': 'Germany',
    'Rheda-Wiedenbrück': 'Germany',
    'Rudolstadt': 'Germany',
    'Neunkirchen-Seelscheid': 'Germany',
    'Tittmoning': 'Germany',
    'Kamen': 'Germany',
    'Haimhausen': 'Germany',
    'Weißwasser': 'Germany',
    'Triberg': 'Germany',
    'Herrsching am Ammersee': 'Germany',
    'Oberndorf am Neckar': 'Germany',
    'Schwäbisch Hall': 'Germany',
    'Tashkent': 'Uzbekistan',
    'Bad Windsheim': 'Germany',
    'Selm': 'Germany',
    'Arnstadt': 'Germany',
    'Neu-Isenburg': 'Germany',
    'Buttstädt': 'Germany',
    'Kaltenkirchen': 'Germany',
    'Neuenkirchen': 'Germany',
    'Eystrup': 'Germany',
    'Kirn': 'Germany',
    'Neunkirchen': 'Germany',
    'Buchholz': 'Germany',
    'Mittweida': 'Germany',
    'Altötting': 'Germany',
    'Saint Petersburg': 'Russia',
    'Bad Emstal': 'Germany',
    'Mandelbachtal': 'Germany',
    'Riga': 'Latvia',
    'Nünchritz': 'Germany',
    'Oelde': 'Germany',
    'Bergheim': 'Germany',
    'London': 'United Kingdom',
    'Mainz-Kostheim': 'Germany',
    'Niedenstein': 'Germany',
    'Kaliningrad': 'Russia',
    'Hilchenbach': 'Germany',
    'Neu Wulmstorf': 'Germany',
    'Bielefeld': 'Germany',
    'Zorneding': 'Germany',
    'Eggenstein-Leopoldshafen': 'Germany',
    'Floß': 'Germany',
    'Rosengarten': 'Germany',
    'Schwaig': 'Germany',
    'Bingen': 'Germany',
    'Tettnang': 'Germany',
    'Wismar': 'Germany',
    'Ahaus': 'Germany',
    'Eppelborn': 'Germany',
    'Dörverden': 'Germany',
    'Bat yam': 'Israel',
    'Rodewisch': 'Germany',
    'Schrozberg': 'Germany',
    'Hoyerswerda': 'Germany',
    'Aschersleben': 'Germany',
    'Teterow': 'Germany',
    'Gera': 'Germany',
    'Backnang': 'Germany',
    'Kamenskoe': 'Ukraine',
    'Kirchlengern': 'Germany',
    'Delitzsch': 'Germany',
    'Walldorf': 'Germany',
    'Königstein im Taunus': 'Germany',
    'Brühl': 'Germany',
    'Neubrandenburg': 'Germany',
    'Viernheim': 'Germany',
    'Fernwald': 'Germany',
    'Hösbach': 'Germany',
    'Kemnath': 'Germany',
    'Neumarkt in der Oberpfalz': 'Germany',
    'Kamenz': 'Germany',
    'Hattgenstein': 'Germany',
    'Neukirchen-Vluyn': 'Germany',
    'Wolnzach': 'Germany',
    'Hofkirchen': 'Germany',
    'Moscow': 'Russia',
    'Nastätten': 'Germany',
    'Zerbst': 'Germany',
    'Grafenau': 'Germany',
    'Albstadt': 'Germany',
    'Postbauer-Heng': 'Germany',
    'Neutraubling': 'Germany',
    'Meinersen': 'Germany',
    'Espenau': 'Germany',
    'Grevenbroich': 'Germany',
    'Deggendorf': 'Germany',
    'Niedereschach': 'Germany',
    'Donauwörth': 'Germany',
    'Haldensleben': 'Germany',
    'Illingen': 'Germany',
    'Norderney': 'Germany',
    'Itzehoe': 'Germany',
    'Münchhausen': 'Germany',
    'Oberrot': 'Germany',
    'Weilheim': 'Germany',
    'Marsberg': 'Germany',
    'Beckingen': 'Germany',
    'Lemgo': 'Germany',
    'Werlte': 'Germany',
    'Pfaffenhofen': 'Germany',
    'Waldenburg': 'Germany',
    'Schieder-Schwalenberg': 'Germany',
    'Nordhausen': 'Germany',
    'Dormagen': 'Germany',
    'Dußlingen': 'Germany',
    'Ottersweier': 'Germany',
    'Voerde': 'Germany',
    'Forst': 'Germany',
    'Seesen': 'Germany',
    'Baesweiler': 'Germany',
    'Nagold': 'Germany',
    'Kleinostheim': 'Germany',
    'Löningen': 'Germany',
    'Unterschneidheim': 'Germany',
    'Sand am Main': 'Germany',
    'Wangen im Allgäu': 'Germany',
    'Maasbree': 'Netherlands',
    'Homburg': 'Germany',
    'Bad Abbach': 'Germany',
    'Lotte': 'Germany',
    'Birkenfeld': 'Germany',
    'Phuket': 'Thailand',
    'Almaty': 'Kazakhstan',
    'Ingolstadt': 'Germany',
    'Böblingen': 'Germany',
    'Adelebsen': 'Germany',
    'Sigmarszell': 'Germany',
    'Neuhäusel': 'Germany',
    'Lehre': 'Germany',
    'Herzogenaurach': 'Germany',
    'Mömlingen': 'Germany',
    'Willich': 'Germany',
    'Dettelbach': 'Germany',
    'Michelstadt': 'Germany',
    'Niesky': 'Germany',
    'Neuwied': 'Germany',
    'Freren': 'Germany',
    'Nienburg/Weser': 'Germany',
    'Heimbach': 'Germany',
    'Euerbach': 'Germany',
    'Waldkraiburg': 'Germany',
    'Saarlouis': 'Germany',
    'Litzendorf': 'Germany',
    'Fröndenberg': 'Germany',
    'Überlingen': 'Germany',
    'Bad Soden am Taunus': 'Germany',
    'Lauf': 'Germany',
    'Anklam': 'Germany',
    'Eislingen': 'Germany',
    'Hachenburg': 'Germany',
    'Pfinztal': 'Germany',
    'Szczecin': 'Poland',
    'Leutkirch im Allgäu': 'Germany',
    'Neusäß': 'Germany',
    'Mühlhausen': 'Germany',
    'Annaberg-Buchholz': 'Germany',
    'Blumberg': 'Germany',
    'Retzstadt': 'Germany',
    'Kolbermoor': 'Germany',
    'Donaueschingen': 'Germany',
    'Gdynia': 'Poland',
    'Rendsburg': 'Germany',
    'Namur': 'Belgium',
    'Dingolfing': 'Germany',
    'Dinkelscherben': 'Germany',
    'Neuburg an der Donau': 'Germany',
    'Halle (Saale)': 'Germany',
    'Sundern': 'Germany',
    'Tübingen': 'Germany',
    'Sexau': 'Germany',
    'Vaihingen an der Enz': 'Germany',
    'Steinbach': 'Germany',
    'Imsbach': 'Germany',
    'Harsewinkel': 'Germany',
    'Bad Feilnbach': 'Germany',
    'Marne': 'Germany',
    'Hückeswagen': 'Germany',
    'Kappelrodeck': 'Germany',
    'Ehrensberg': 'Germany',
    'Dettenhausen': 'Germany',
    'Wittstock': 'Germany',
    'Vellberg': 'Germany',
    'Bad Vilbel': 'Germany',
    'Kluse': 'Germany',
    'Hockenheim': 'Germany',
    'Runkel': 'Germany',
    'Włodawa': 'Poland',
    'Kelkheim': 'Germany',
    'Viereth-Trunstadt': 'Germany',
    'Nellingen': 'Germany',
    'Fürstenfeldbruck': 'Germany',
    'Glandorf': 'Germany',
    'Nisterberg': 'Germany',
    'Landsberg am Lech': 'Germany',
    'Bamberg': 'Germany',
    'Kernen im Remstal': 'Germany',
    'Nottuln': 'Germany',
    'Hechingen': 'Germany',
    'Marktredwitz': 'Germany',
    'Beilstein': 'Germany',
    'Heusweiler': 'Germany',
    'Aidlingen': 'Germany',
    'Elze': 'Germany',
    'Borken': 'Germany',
    'Bernau': 'Germany',
    'Pyrbaum': 'Germany',
    'Niederstotzingen': 'Germany',
    'Porta Westfalica': 'Germany',
    'Wülfrath': 'Germany',
    'Volgodonsk': 'Russia',
    'Müllrose': 'Germany',
    'Burg': 'Germany',
    'Hüttisheim': 'Germany',
    'Königslutter': 'Germany',
    'Melsungen': 'Germany',
    'Bitterfeld-Wolfen': 'Germany',
    'Uhldingen-Mühlhofen': 'Germany',
    'Grafenhausen': 'Germany',
    'Freudenstadt': 'Germany',
    'Mengerskirchen': 'Germany',
    'Heppenheim': 'Germany',
    'Nürtingen': 'Germany',
    'Rothenburg ob der Tauber': 'Germany',
    'Sasbach': 'Germany',
    'Malchin': 'Germany',
    'Schmölln': 'Germany',
    'Lengenfeld': 'Germany',
    'Miesbach': 'Germany',
    'Holzminden': 'Germany',
    'Gröbenzell': 'Germany',
    'Mettmann': 'Germany',
    'Eching': 'Germany',
    'Manching': 'Germany',
    'Karben': 'Germany',
    'Mainaschaff': 'Germany',
    'Baden-Baden': 'Germany',
    'Dubai': 'United Arab Emirates',
    'Miltenberg': 'Germany',
    'Wetter': 'Germany',
    'Garbsen': 'Germany',
    'Kirchheim bei München': 'Germany',
    'Prenzlau': 'Germany',
    'Odelzhausen': 'Germany',
    'Urbach': 'Germany',
    'Schönwald': 'Germany',
    'Altlandsberg': 'Germany',
    'Hopfen am See': 'Germany',
    'Schwäbisch Gmünd': 'Germany',
    'Boppard': 'Germany',
    'Wertheim': 'Germany',
    'Sindelfingen': 'Germany',
    'Pirmasens': 'Germany',
    'Rosbach vor der Höhe': 'Germany',
    'Neuenrade': 'Germany',
    'Hagenow': 'Germany',
    'Kaufbeuren': 'Germany',
    'Osterhofen': 'Germany',
    'Rotenburg an der Fulda': 'Germany',
    'Hofheim am Taunus': 'Germany',
    'Krumbach': 'Germany',
    'Bretten': 'Germany',
    'Langenbach': 'Germany',
    'Stadecken-Elsheim': 'Germany',
    'Oerlinghausen': 'Germany',
    'Göttingen': 'Germany',
    'Lampertheim': 'Germany',
    'Steinau an der Straße': 'Germany',
    'Wolfhagen': 'Germany',
    'Plauen': 'Germany',
    'Sulzbach': 'Germany',
    'Herzberg': 'Germany',
    'Biberach': 'Germany',
    'Schmallenberg': 'Germany',
    'Gelsenkirchen': 'Germany',
    'Verden': 'Germany',
    'Salzgitter': 'Germany',
    'Furtwangen': 'Germany',
    'Isernhagen': 'Germany',
    'Schonach im Schwarzwald': 'Germany',
    'Kobyłka': 'Poland',
    'Erkelenz': 'Germany',
    'Heide': 'Germany',
    'Mainbernheim': 'Germany',
    'Bopfingen': 'Germany',
    'Bremerhaven': 'Germany',
    'Ampfing': 'Germany',
    'Hohenberg an der Eger': 'Germany',
    'Leopoldshöhe': 'Germany',
    'Bergneustadt': 'Germany',
    'Offenbach': 'Germany',
    'Hennigsdorf': 'Germany',
    'Schliersee': 'Germany',
    'Gaildorf': 'Germany',
    'Bad Gottleuba-Berggießhübel': 'Germany',
    'Kitzingen': 'Germany',
    'Lennestadt': 'Germany',
    'Weinsberg': 'Germany',
    'Kaiserslautern': 'Germany',
    'Plön': 'Germany',
    'Wittendörp': 'Germany',
    'Konz': 'Germany',
    'Landau in der Pfalz': 'Germany',
    'Nordenham': 'Germany',
    'Raschau-Markersbach': 'Germany',
    'Wirges': 'Germany',
    'Lörrach': 'Germany',
    'Öhringen': 'Germany',
    'Zetel': 'Germany',
    'Weimar': 'Germany',
    'Bobingen': 'Germany',
    'Wemding': 'Germany',
    'Sankt Augustin': 'Germany',
    'Haselünne': 'Germany',
    'Maikammer': 'Germany',
    'Oberkochen': 'Germany',
    'Siegburg': 'Germany',
    'Greven': 'Germany',
    'Birstein': 'Germany',
    'Altenburg': 'Germany',
    'Brakel': 'Germany',
    'Pinneberg': 'Germany',
    'Ladenburg': 'Germany',
    'Bad Schwalbach': 'Germany',
    'Mahlberg': 'Germany',
    'Leverkusen': 'Germany',
    'Pavlograd': 'Ukraine',
    'Mühldorf': 'Germany',
    'Starnberg': 'Germany',
    'Meißenheim': 'Germany',
    'Rommerskirchen': 'Germany',
    'Lychen': 'Germany',
    'Zella-Mehlis': 'Germany',
    'Lutherstadt Eisleben': 'Germany',
    'Eiterfeld': 'Germany',
    'Neustadt-Glewe': 'Germany',
    'Finnentrop': 'Germany',
    'Thalmassing': 'Germany',
    'Przesław': 'Poland',
    'Ahrensburg': 'Germany',
    'Bad Hindelang': 'Germany',
    'Bad Blankenburg': 'Germany',
    'Germersheim': 'Germany',
    'Montabaur': 'Germany',
    'Bürstadt': 'Germany',
    'Hasbergen': 'Germany',
    'Bad Ems': 'Germany',
    'Bad Essen': 'Germany',
    'Norden': 'Germany',
    'Heiligenhaus': 'Germany',
    'Mutlangen': 'Germany',
    'Edingen-Neckarhausen': 'Germany',
    'Sonneberg': 'Germany',
    'Recklinghausen': 'Germany',
    'Delmenhorst': 'Germany',
    'Freising': 'Germany',
    'Peine': 'Germany',
    'Altshausen': 'Germany',
    'Baiersbronn': 'Germany',
    'Lüdenscheid': 'Germany',
    'Alsbach-Hähnlein': 'Germany',
    'Schenefeld': 'Germany',
    'Hallbergmoos': 'Germany',
    'Burbach': 'Germany',
    'Waldkirch': 'Germany',
    'Stuhr': 'Germany',
    'Bad Wildungen': 'Germany',
    'Warendorf': 'Germany',
    'Winhöring': 'Germany',
    'Erlangen': 'Germany',
    'Pößneck': 'Germany',
    'Tengen': 'Germany',
    'Saalfeld': 'Germany',
    'Olching': 'Germany',
    'Berchtesgaden': 'Germany',
    'Lage': 'Germany',
    'Freigericht': 'Germany',
    'Bad Friedrichshall': 'Germany',
    'Reichenbach': 'Germany',
    'Causeni': 'Moldova',
    'Bruchköbel': 'Germany',
    'Schwepnitz': 'Germany',
    'Quickborn': 'Germany',
    'Radebeul': 'Germany',
    'Korbach': 'Germany',
    'Landau an der Isar': 'Germany',
    'Emden': 'Germany',
    'Eisenbach (Hochschwarzwald)': 'Germany',
    'Hohenstein': 'Germany',
    'Duderstadt': 'Germany',
    'Chuguev': 'Ukraine',
    'Lindau (Bodensee)': 'Germany',
    'Bad Hönningen': 'Germany',
    'Senftenberg': 'Germany',
    'Günzburg': 'Germany',
    'Malschwitz': 'Germany',
    'Tutzing': 'Germany',
    'Blankenburg': 'Germany',
    'Eschenburg': 'Germany',
    'Netphen': 'Germany',
    'Apen': 'Germany',
    'Kharkiv': 'Ukraine',
    'Wittmund': 'Germany',
    'Novorossiysk': 'Russia',
    'Jördenstorf': 'Germany',
    'Werne': 'Germany',
    'Melle': 'Germany',
    'Lüneburg': 'Germany',
    'Bruck': 'Germany',
    'Prostejov': 'Czech Republic',
    'Wenden': 'Germany',
    'Belgrade': 'Serbia',
    'Alamudun': 'Kyrgyzstan',
    'Bad Gandersheim': 'Germany',
    'Braubach': 'Germany',
    'Geldern': 'Germany',
    'Bassum': 'Germany',
    'Brake': 'Germany'
}