city_to_state = {
    'Crailsheim': 'Baden-Württemberg',
    'Dortmund': 'Nordrhein-Westfalen',
    'Stuttgart': 'Baden-Württemberg',
    'München': 'Bayern',
    'Berlin': 'Berlin',
    'Offenbach am Main': 'Hessen',
    'Eberbach': 'Baden-Württemberg',
    'Görlitz': 'Sachsen',
    'Pfedelbach': 'Baden-Württemberg',
    'Unterhaching': 'Bayern',
    'Rüdesheim am Rhein': 'Hessen',
    'Dresden': 'Sachsen',
    'Gummersbach': 'Nordrhein-Westfalen',
    'Kassel': 'Hessen',
    'Wenzenbach': 'Bayern',
    'Merseburg': 'Sachsen-Anhalt',
    'Gommern': 'Sachsen-Anhalt',
    'Pommelsbrunn': 'Bayern',
    'Duisburg': 'Nordrhein-Westfalen',
    'Herzogenrath': 'Nordrhein-Westfalen',
    'Schwandorf': 'Bayern',
    'Mainz': 'Rheinland-Pfalz',
    'Zinnowitz': 'Mecklenburg-Vorpommern',
    'Quedlinburg': 'Sachsen-Anhalt',
    'Wolfsburg': 'Niedersachsen',
    'Weilburg': 'Hessen',
    'Dillenburg': 'Hessen',
    'Neu-Ulm': 'Bayern',
    'Lauter-Bernsbach': 'Sachsen',
    'Bonn': 'Nordrhein-Westfalen',
    'Riedstadt': 'Hessen',
    'Rosenheim': 'Bayern',
    'Mönchengladbach': 'Nordrhein-Westfalen',
    'Neuburg': 'Bayern',
    'Rostock': 'Mecklenburg-Vorpommern',
    'Bad Oeynhausen': 'Nordrhein-Westfalen',
    'Chemnitz': 'Sachsen',
    'Diez': 'Rheinland-Pfalz',
    'Nürnberg': 'Bayern',
    'Laubach': 'Hessen',
    'Düren': 'Nordrhein-Westfalen',
    'Düsseldorf': 'Nordrhein-Westfalen',
    'Zwickau': 'Sachsen',
    'Bremen': 'Bremen',
    'Halle': 'Sachsen-Anhalt',
    'Erbach': 'Hessen',
    'Jünkerath': 'Rheinland-Pfalz',
    'Magdeburg': 'Sachsen-Anhalt',
    'Celle': 'Niedersachsen',
    'Germering': 'Bayern',
    'Kleve': 'Nordrhein-Westfalen',
    'Leinfelden-Echterdingen': 'Baden-Württemberg',
    'Garmisch-Partenkirchen': 'Bayern',
    'Leipzig': 'Sachsen',
    'Hof': 'Bayern',
    'Lünen': 'Nordrhein-Westfalen',
    'Murr': 'Baden-Württemberg',
    'Bochum': 'Nordrhein-Westfalen',
    'Leonberg': 'Baden-Württemberg',
    'Bad Homburg vor der Höhe': 'Hessen',
    'Kiel': 'Schleswig-Holstein',
    'Theres': 'Bayern',
    'Lüchow': 'Niedersachsen',
    'Stolberg': 'Nordrhein-Westfalen',
    'Bautzen': 'Sachsen',
    'Weiden': 'Bayern',
    'Osterode am Harz': 'Niedersachsen',
    'Göppingen': 'Baden-Württemberg',
    'Ansbach': 'Bayern',
    'Aachen': 'Nordrhein-Westfalen',
    'Menden': 'Nordrhein-Westfalen',
    'Iserlohn': 'Nordrhein-Westfalen',
    'Aying': 'Bayern',
    'Mannheim': 'Baden-Württemberg',
    'Hamburg': 'Hamburg',
    'Einhausen': 'Hessen',
    'Minden': 'Nordrhein-Westfalen',
    'Süßen': 'Baden-Württemberg',
    'Flensburg': 'Schleswig-Holstein',
    'Tönning': 'Schleswig-Holstein',
    'Aschaffenburg': 'Bayern',
    'Holzwickede': 'Nordrhein-Westfalen',
    'Villingen-Schwenningen': 'Baden-Württemberg',
    'Ochtrup': 'Nordrhein-Westfalen',
    'Klosterlechfeld': 'Bayern',
    'Straubing': 'Bayern',
    'Augsburg': 'Bayern',
    'Rheine': 'Nordrhein-Westfalen',
    'Singen': 'Baden-Württemberg',
    'Werl': 'Nordrhein-Westfalen',
    'Schweinfurt': 'Bayern',
    'Ditzingen': 'Baden-Württemberg',
    'Frankfurt': 'Hessen',
    'Waldbronn': 'Baden-Württemberg',
    'Bad Wildbad im Schwarzwald': 'Baden-Württemberg',
    'Essen': 'Nordrhein-Westfalen',
    'Weil am Rhein': 'Baden-Württemberg',
    'Lahnstein': 'Rheinland-Pfalz',
    'Osnabrück': 'Niedersachsen',
    'Lierschied': 'Rheinland-Pfalz',
    'Eggenfelden': 'Bayern',
    'Trebgast': 'Bayern',
    'Verl': 'Nordrhein-Westfalen',
    'Wesel': 'Nordrhein-Westfalen',
    'Frammersbach': 'Bayern',
    'Grevesmühlen': 'Mecklenburg-Vorpommern',
    'Perleberg': 'Brandenburg',
    'Michelfeld': 'Baden-Württemberg',
    'Stralsund': 'Mecklenburg-Vorpommern',
    'Zeitz': 'Sachsen-Anhalt',
    'Münster': 'Nordrhein-Westfalen',
    'Helmstedt': 'Niedersachsen',
    'Krefeld': 'Nordrhein-Westfalen',
    'Rastatt': 'Baden-Württemberg',
    'Detmold': 'Nordrhein-Westfalen',
    'Weinstadt': 'Baden-Württemberg',
    'Friedrichshafen': 'Baden-Württemberg',
    'Wächtersbach': 'Hessen',
    'Weißenburg in Bayern': 'Bayern',
    'Solingen': 'Nordrhein-Westfalen',
    'Worms': 'Rheinland-Pfalz',
    'Schlangen': 'Nordrhein-Westfalen',
    'Schwarzenberg': 'Sachsen',
    'Ludwigsburg': 'Baden-Württemberg',
    'Büchen': 'Schleswig-Holstein',
    'Remscheid': 'Nordrhein-Westfalen',
    'Kulmbach': 'Bayern',
    'Burghausen': 'Bayern',
    'Meinerzhagen': 'Nordrhein-Westfalen',
    'Torgau': 'Sachsen',
    'Coesfeld': 'Nordrhein-Westfalen',
    'Hartmannsdorf': 'Sachsen',
    'Adelschlag': 'Bayern',
    'Eisenberg': 'Thüringen',
    'Kehl': 'Baden-Württemberg',
    'Delbrück': 'Nordrhein-Westfalen',
    'Kempten': 'Bayern',
    'Marburg': 'Hessen',
    'Oranienburg': 'Brandenburg',
    'Siegen': 'Nordrhein-Westfalen',
    'Castrop-Rauxel': 'Nordrhein-Westfalen',
    'Kalkar': 'Nordrhein-Westfalen',
    'Würzburg': 'Bayern',
    'Molsberg': 'Rheinland-Pfalz',
    'Rust': 'Baden-Württemberg',
    'Bad Hersfeld': 'Hessen',
    'Südlohn': 'Nordrhein-Westfalen',
    'Erfurt': 'Thüringen',
    'Wiesenttal': 'Bayern',
    'Altenstadt': 'Hessen',
    'Sankt Leon-Rot': 'Baden-Württemberg',
    'Friedrichsdorf': 'Hessen',
    'Heinsberg': 'Nordrhein-Westfalen',
    'Passau': 'Bayern',
    'Darmstadt': 'Hessen',
    'Ruhla': 'Thüringen',
    'Bad Nauheim': 'Hessen',
    'Bärnau': 'Bayern',
    'Erftstadt': 'Nordrhein-Westfalen',
    'Arnsberg': 'Nordrhein-Westfalen',
    'Pullach im Isartal': 'Bayern',
    'Gelnhausen': 'Hessen',
    'Liederbach am Taunus': 'Hessen',
    'Gröditz': 'Sachsen',
    'Trier': 'Rheinland-Pfalz',
    'Buxtehude': 'Niedersachsen',
    'Uelzen': 'Niedersachsen',
    'Aldenhoven': 'Nordrhein-Westfalen',
    'Lutherstadt Wittenberg': 'Sachsen-Anhalt',
    'Friedenweiler': 'Baden-Württemberg',
    'Witzeeze': 'Schleswig-Holstein',
    'Neuss': 'Nordrhein-Westfalen',
    'Pforzheim': 'Baden-Württemberg',
    'Königswinter': 'Nordrhein-Westfalen',
    'Northeim': 'Niedersachsen',
    'Rohrdorf': 'Bayern',
    'Filderstadt': 'Baden-Württemberg',
    'Fürth': 'Bayern',
    'Kerpen': 'Nordrhein-Westfalen',
    'Markdorf': 'Baden-Württemberg',
    'Hannover': 'Niedersachsen',
    'Mülheim an der Ruhr': 'Nordrhein-Westfalen',
    'Erkner': 'Brandenburg',
    'Monschau': 'Nordrhein-Westfalen',
    'Bad Segeberg': 'Schleswig-Holstein',
    'Lauf an der Pegnitz': 'Bayern',
    'Oberasbach': 'Bayern',
    'Naumburg': 'Sachsen-Anhalt',
    'Wandlitz': 'Brandenburg',
    'Witten': 'Nordrhein-Westfalen',
    'Obernheim': 'Baden-Württemberg',
    'Wilhelmshaven': 'Niedersachsen',
    'Heimbuchenthal': 'Bayern',
    'Weiterstadt': 'Hessen',
    'Braunfels': 'Hessen',
    'Salzwedel': 'Sachsen-Anhalt',
    'Freiburg': 'Baden-Württemberg',
    'Regensburg': 'Bayern',
    'Leer': 'Niedersachsen',
    'Höhenkirchen-Siegertsbrunn': 'Bayern',
    'Coburg': 'Bayern',
    'Wolfenbüttel': 'Niedersachsen',
    'Niederorschel': 'Thüringen',
    'Vierden': 'Niedersachsen',
    'Ostbevern': 'Nordrhein-Westfalen',
    'Bad Pyrmont': 'Niedersachsen',
    'Stelle': 'Niedersachsen',
    'Wadgassen': 'Saarland',
    'Leingarten': 'Baden-Württemberg',
    'Obermarchtal': 'Baden-Württemberg',
    'Güglingen': 'Baden-Württemberg',
    'Sankt Ingbert': 'Saarland',
    'Staufen im Breisgau': 'Baden-Württemberg',
    'Erlensee': 'Hessen',
    'Erkrath': 'Nordrhein-Westfalen',
    'Kornwestheim': 'Baden-Württemberg',
    'Wiesbaden': 'Hessen',
    'Leutershausen': 'Bayern',
    'Rees': 'Nordrhein-Westfalen',
    'Schwerin': 'Mecklenburg-Vorpommern',
    'Reutlingen': 'Baden-Württemberg',
    'Hamm': 'Nordrhein-Westfalen',
    'Köln': 'Nordrhein-Westfalen',
    'Allendorf': 'Hessen',
    'Gladenbach': 'Hessen',
    'Euskirchen': 'Nordrhein-Westfalen',
    'Gerlingen': 'Baden-Württemberg',
    'Lübeck': 'Schleswig-Holstein',
    'Büren': 'Nordrhein-Westfalen',
    'Ganderkesee': 'Niedersachsen',
    'Ohrdruf': 'Thüringen',
    'Beverungen': 'Nordrhein-Westfalen',
    'Oldenburg': 'Niedersachsen',
    'Usingen': 'Hessen',
    'Geilenkirchen': 'Nordrhein-Westfalen',
    'Leichlingen': 'Nordrhein-Westfalen',
    'Veldenz': 'Rheinland-Pfalz',
    'Werder': 'Brandenburg',
    'Morsbach': 'Nordrhein-Westfalen',
    'Herdecke': 'Nordrhein-Westfalen',
    'Gießen': 'Hessen',
    'Seevetal': 'Niedersachsen',
    'Korschenbroich': 'Nordrhein-Westfalen',
    'Stendal': 'Sachsen-Anhalt',
    'Teublitz': 'Bayern',
    'Meerbusch': 'Nordrhein-Westfalen',
    'Obergünzburg': 'Bayern',
    'Eggolsheim': 'Bayern',
    'Limbach-Oberfrohna': 'Sachsen',
    'Kraichtal': 'Baden-Württemberg',
    'Rathenow': 'Brandenburg',
    'Mülheim-Kärlich': 'Rheinland-Pfalz',
    'Babenhausen': 'Hessen',
    'Heidenheim': 'Baden-Württemberg',
    'Cremlingen': 'Niedersachsen',
    'Hörstel': 'Nordrhein-Westfalen',
    'Rinteln': 'Niedersachsen',
    'Gütersloh': 'Nordrhein-Westfalen',
    'Röttingen': 'Bayern',
    'Bayreuth': 'Bayern',
    'Hagen': 'Nordrhein-Westfalen',
    'Rötgesbüttel': 'Niedersachsen',
    'Parchim': 'Mecklenburg-Vorpommern',
    'Emsdetten': 'Nordrhein-Westfalen',
    'Randersacker': 'Bayern',
    'Erding': 'Bayern',
    'Kressbronn am Bodensee': 'Baden-Württemberg',
    'Essing': 'Bayern',
    'Nesselwang': 'Bayern',
    'Braunschweig': 'Niedersachsen',
    'Karlsfeld': 'Bayern',
    'Nuenchritz': 'Sachsen',
    'Obergriesbach': 'Bayern',
    'Karlsruhe': 'Baden-Württemberg',
    'Paderborn': 'Nordrhein-Westfalen',
    'Remchingen': 'Baden-Württemberg',
    'Großrosseln': 'Saarland',
    'Neuhemsbach': 'Rheinland-Pfalz',
    'Nebra (Unstrut)': 'Sachsen-Anhalt',
    'Herford': 'Nordrhein-Westfalen',
    'Neumünster': 'Schleswig-Holstein',
    'Hennef': 'Nordrhein-Westfalen',
    'Wörthsee': 'Bayern',
    'Monheim am Rhein': 'Nordrhein-Westfalen',
    'Troisdorf': 'Nordrhein-Westfalen',
    'Henstedt-Ulzburg': 'Schleswig-Holstein',
    'Achberg': 'Baden-Württemberg',
    'Königsmoos': 'Bayern',
    'Warburg': 'Nordrhein-Westfalen',
    'Stade': 'Niedersachsen',
    'Großbreitenbach': 'Thüringen',
    'Bad Driburg': 'Nordrhein-Westfalen',
    'Sollstedt': 'Thüringen',
    'Esslingen am Neckar': 'Baden-Württemberg',
    'Cloppenburg': 'Niedersachsen',
    'Landshut': 'Bayern',
    'Karstädt': 'Brandenburg',
    'Steinfurt': 'Nordrhein-Westfalen',
    'Gerolstein': 'Rheinland-Pfalz',
    'Schwanewede': 'Niedersachsen',
    'Hückelhoven': 'Nordrhein-Westfalen',
    'Schwarzheide': 'Brandenburg',
    'Böhlen': 'Sachsen',
    'Pleinfeld': 'Bayern',
    'Hettenshausen': 'Bayern',
    'Bünde': 'Nordrhein-Westfalen',
    'Sankt Georgen im Schwarzwald': 'Baden-Württemberg',
    'Lichtenfels': 'Bayern',
    'Fulda': 'Hessen',
    'Riesa': 'Sachsen',
    'Löbau': 'Sachsen',
    'Waren': 'Mecklenburg-Vorpommern',
    'Hameln': 'Niedersachsen',
    'Aichwald': 'Baden-Württemberg',
    'Eppelheim': 'Baden-Württemberg',
    'Bad Berleburg': 'Nordrhein-Westfalen',
    'Aalen': 'Baden-Württemberg',
    'Oberding': 'Bayern',
    'Wermelskirchen': 'Nordrhein-Westfalen',
    'Trossingen': 'Baden-Württemberg',
    'Stein': 'Bayern',
    'Bad Wörishofen': 'Bayern',
    'Twistringen': 'Niedersachsen',
    'Langenselbold': 'Hessen',
    'Alsfeld': 'Hessen',
    'Limeshain': 'Hessen',
    'Alfeld': 'Niedersachsen',
    'Forchheim': 'Bayern',
    'Altenkirchen': 'Rheinland-Pfalz',
    'Velden': 'Bayern',
    'Alzenau in Unterfranken': 'Bayern',
    'Bühl': 'Baden-Württemberg',
    'Bad Tölz': 'Bayern',
    'Schkeuditz': 'Sachsen',
    'Poing': 'Bayern',
    'Tuttlingen': 'Baden-Württemberg',
    'Cuxhaven': 'Niedersachsen',
    'Kirchlauter': 'Bayern',
    'Speyer': 'Rheinland-Pfalz',
    'Untersiemau': 'Bayern',
    'Pfalzgrafenweiler': 'Baden-Württemberg',
    'Wetzlar': 'Hessen',
    'Reichenau': 'Baden-Württemberg',
    'Scharbeutz': 'Schleswig-Holstein',
    'Kirchheim': 'Baden-Württemberg',
    'Blankenfelde': 'Brandenburg',
    'Güstrow': 'Mecklenburg-Vorpommern',
    'Frechen': 'Nordrhein-Westfalen',
    'Vechta': 'Niedersachsen',
    'Leuna': 'Sachsen-Anhalt',
    'Coswig': 'Sachsen',
    'Kisslegg': 'Baden-Württemberg',
    'Ebern': 'Bayern',
    'Weilheim in Oberbayern': 'Bayern',
    'Engen': 'Baden-Württemberg',
    'Lippstadt': 'Nordrhein-Westfalen',
    'Konstanz': 'Baden-Württemberg',
    'Saarbrücken': 'Saarland',
    'Aichach': 'Bayern',
    'Heilbronn': 'Baden-Württemberg',
    'Sandersdorf': 'Sachsen-Anhalt',
    'Luckenwalde': 'Brandenburg',
    'Inchenhofen': 'Bayern',
    'Amberg': 'Bayern',
    'Oberhausen': 'Nordrhein-Westfalen',
    'Waiblingen': 'Baden-Württemberg',
    'Appen': 'Schleswig-Holstein',
    'Nettetal': 'Nordrhein-Westfalen',
    'Kirchlinteln': 'Niedersachsen',
    'Ottobrunn': 'Bayern',
    'Koblenz': 'Rheinland-Pfalz',
    'Kusel': 'Rheinland-Pfalz',
    'Massenbachhausen': 'Baden-Württemberg',
    'Rangsdorf': 'Brandenburg',
    'Hildesheim': 'Niedersachsen',
    'Heidelberg': 'Baden-Württemberg',
    'Senden': 'Bayern',
    'Borna': 'Sachsen',
    'Bad Saulgau': 'Baden-Württemberg',
    'Cham': 'Bayern',
    'Herne': 'Nordrhein-Westfalen',
    'Lenningen': 'Baden-Württemberg',
    'Niederstetten': 'Baden-Württemberg',
    'Olpe': 'Nordrhein-Westfalen',
    'Heinersreuth': 'Bayern',
    'Speichersdorf': 'Bayern',
    'Potsdam': 'Brandenburg',
    'Bergisch Gladbach': 'Nordrhein-Westfalen',
    'Weingarten': 'Baden-Württemberg',
    'Brandenburg an der Havel': 'Brandenburg',
    'Lengerich': 'Nordrhein-Westfalen',
    'Poppenhausen': 'Hessen',
    'Friesoythe': 'Niedersachsen',
    'Lingen': 'Niedersachsen',
    'Jena': 'Thüringen',
    'Griepswohld': 'Schleswig-Holstein',
    'Garrel': 'Niedersachsen',
    'Herbrechtingen': 'Baden-Württemberg',
    'Binzen': 'Baden-Württemberg',
    'Friedberg': 'Bayern',
    'Wuppertal': 'Nordrhein-Westfalen',
    'Ulm': 'Baden-Württemberg',
    'Markgröningen': 'Baden-Württemberg',
    'Dinslaken': 'Nordrhein-Westfalen',
    'Ravensburg': 'Baden-Württemberg',
    'Geyer': 'Sachsen',
    'Ilmenau': 'Thüringen',
    'Freital': 'Sachsen',
    'Engelsbrand': 'Baden-Württemberg',
    'Planegg': 'Bayern',
    'Zwingenberg': 'Hessen',
    'Abensberg': 'Bayern',
    'Weinähr': 'Rheinland-Pfalz',
    'Wiefelstede': 'Niedersachsen',
    'Fritzlar': 'Hessen',
    'Rheda-Wiedenbrück': 'Nordrhein-Westfalen',
    'Rudolstadt': 'Thüringen',
    'Neunkirchen-Seelscheid': 'Nordrhein-Westfalen',
    'Tittmoning': 'Bayern',
    'Kamen': 'Nordrhein-Westfalen',
    'Haimhausen': 'Bayern',
    'Weißwasser': 'Sachsen',
    'Triberg': 'Baden-Württemberg',
    'Herrsching am Ammersee': 'Bayern',
    'Oberndorf am Neckar': 'Baden-Württemberg',
    'Schwäbisch Hall': 'Baden-Württemberg',
    'Bad Windsheim': 'Bayern',
    'Selm': 'Nordrhein-Westfalen',
    'Arnstadt': 'Thüringen',
    'Neu-Isenburg': 'Hessen',
    'Buttstädt': 'Thüringen',
    'Kaltenkirchen': 'Schleswig-Holstein',
    'Neuenkirchen': 'Nordrhein-Westfalen',
    'Eystrup': 'Niedersachsen',
    'Kirn': 'Rheinland-Pfalz',
    'Neunkirchen': 'Saarland',
    'Buchholz': 'Niedersachsen',
    'Mittweida': 'Sachsen',
    'Altötting': 'Bayern',
    'Bad Emstal': 'Hessen',
    'Mandelbachtal': 'Saarland',
    'Nünchritz': 'Sachsen',
    'Oelde': 'Nordrhein-Westfalen',
    'Bergheim': 'Nordrhein-Westfalen',
    'Niedenstein': 'Hessen',
    'Hilchenbach': 'Nordrhein-Westfalen',
    'Neu Wulmstorf': 'Niedersachsen',
    'Bielefeld': 'Nordrhein-Westfalen',
    'Zorneding': 'Bayern',
    'Eggenstein-Leopoldshafen': 'Baden-Württemberg',
    'Floß': 'Bayern',
    'Rosengarten': 'Niedersachsen',
    'Schwaig': 'Bayern',
    'Bingen': 'Rheinland-Pfalz',
    'Tettnang': 'Baden-Württemberg',
    'Wismar': 'Mecklenburg-Vorpommern',
    'Ahaus': 'Nordrhein-Westfalen',
    'Eppelborn': 'Saarland',
    'Dörverden': 'Niedersachsen',
    'Rodewisch': 'Sachsen',
    'Schrozberg': 'Baden-Württemberg',
    'Hoyerswerda': 'Sachsen',
    'Aschersleben': 'Sachsen-Anhalt',
    'Teterow': 'Mecklenburg-Vorpommern',
    'Gera': 'Thüringen',
    'Backnang': 'Baden-Württemberg',
    'Kirchlengern': 'Nordrhein-Westfalen',
    'Delitzsch': 'Sachsen',
    'Walldorf': 'Baden-Württemberg',
    'Königstein im Taunus': 'Hessen',
    'Brühl': 'Nordrhein-Westfalen',
    'Neubrandenburg': 'Mecklenburg-Vorpommern',
    'Viernheim': 'Hessen',
    'Fernwald': 'Hessen',
    'Hösbach': 'Bayern',
    'Kemnath': 'Bayern',
    'Neumarkt in der Oberpfalz': 'Bayern',
    'Kamenz': 'Sachsen',
    'Hattgenstein': 'Rheinland-Pfalz',
    'Neukirchen-Vluyn': 'Nordrhein-Westfalen',
    'Wolnzach': 'Bayern',
    'Hofkirchen': 'Bayern',
    'Nastätten': 'Rheinland-Pfalz',
    'Zerbst': 'Sachsen-Anhalt',
    'Grafenau': 'Bayern',
    'Albstadt': 'Baden-Württemberg',
    'Postbauer-Heng': 'Bayern',
    'Neutraubling': 'Bayern',
    'Meinersen': 'Niedersachsen',
    'Espenau': 'Hessen',
    'Grevenbroich': 'Nordrhein-Westfalen',
    'Deggendorf': 'Bayern',
    'Niedereschach': 'Baden-Württemberg',
    'Donauwörth': 'Bayern',
    'Haldensleben': 'Sachsen-Anhalt',
    'Illingen': 'Saarland',
    'Norderney': 'Niedersachsen',
    'Itzehoe': 'Schleswig-Holstein',
    'Münchhausen': 'Hessen',
    'Oberrot': 'Baden-Württemberg',
    'Weilheim': 'Baden-Württemberg',
    'Marsberg': 'Nordrhein-Westfalen',
    'Beckingen': 'Saarland',
    'Lemgo': 'Nordrhein-Westfalen',
    'Werlte': 'Niedersachsen',
    'Pfaffenhofen': 'Bayern',
    'Waldenburg': 'Baden-Württemberg',
    'Schieder-Schwalenberg': 'Nordrhein-Westfalen',
    'Nordhausen': 'Thüringen',
    'Dormagen': 'Nordrhein-Westfalen',
    'Dußlingen': 'Baden-Württemberg',
    'Ottersweier': 'Baden-Württemberg',
    'Voerde': 'Nordrhein-Westfalen',
    'Forst': 'Brandenburg',
    'Seesen': 'Niedersachsen',
    'Baesweiler': 'Nordrhein-Westfalen',
    'Nagold': 'Baden-Württemberg',
    'Kleinostheim': 'Bayern',
    'Löningen': 'Niedersachsen',
    'Unterschneidheim': 'Baden-Württemberg',
    'Sand am Main': 'Bayern',
    'Wangen im Allgäu': 'Baden-Württemberg',
    'Homburg': 'Saarland',
    'Bad Abbach': 'Bayern',
    'Lotte': 'Nordrhein-Westfalen',
    'Birkenfeld': 'Rheinland-Pfalz',
    'Ingolstadt': 'Bayern',
    'Böblingen': 'Baden-Württemberg',
    'Adelebsen': 'Niedersachsen',
    'Sigmarszell': 'Bayern',
    'Neuhäusel': 'Rheinland-Pfalz',
    'Lehre': 'Niedersachsen',
    'Herzogenaurach': 'Bayern',
    'Mömlingen': 'Bayern',
    'Willich': 'Nordrhein-Westfalen',
    'Dettelbach': 'Bayern',
    'Michelstadt': 'Hessen',
    'Niesky': 'Sachsen',
    'Neuwied': 'Rheinland-Pfalz',
    'Freren': 'Niedersachsen',
    'Nienburg/Weser': 'Niedersachsen',
    'Heimbach': 'Nordrhein-Westfalen',
    'Euerbach': 'Bayern',
    'Waldkraiburg': 'Bayern',
    'Saarlouis': 'Saarland',
    'Litzendorf': 'Bayern',
    'Fröndenberg': 'Nordrhein-Westfalen',
    'Überlingen': 'Baden-Württemberg',
    'Bad Soden am Taunus': 'Hessen',
    'Lauf': 'Bayern',
    'Anklam': 'Mecklenburg-Vorpommern',
    'Eislingen': 'Baden-Württemberg',
    'Hachenburg': 'Rheinland-Pfalz',
    'Pfinztal': 'Baden-Württemberg',
    'Leutkirch im Allgäu': 'Baden-Württemberg',
    'Neusäß': 'Bayern',
    'Mühlhausen': 'Thüringen',
    'Annaberg-Buchholz': 'Sachsen',
    'Blumberg': 'Baden-Württemberg',
    'Retzstadt': 'Bayern',
    'Kolbermoor': 'Bayern',
    'Donaueschingen': 'Baden-Württemberg',
    'Rendsburg': 'Schleswig-Holstein',
    'Dingolfing': 'Bayern',
    'Dinkelscherben': 'Bayern',
    'Neuburg an der Donau': 'Bayern',
    'Halle (Saale)': 'Sachsen-Anhalt',
    'Sundern': 'Nordrhein-Westfalen',
    'Tübingen': 'Baden-Württemberg',
    'Sexau': 'Baden-Württemberg',
    'Vaihingen an der Enz': 'Baden-Württemberg',
    'Steinbach': 'Hessen',
    'Imsbach': 'Rheinland-Pfalz',
    'Harsewinkel': 'Nordrhein-Westfalen',
    'Bad Feilnbach': 'Bayern',
    'Marne': 'Schleswig-Holstein',
    'Hückeswagen': 'Nordrhein-Westfalen',
    'Kappelrodeck': 'Baden-Württemberg',
    'Dettenhausen': 'Baden-Württemberg',
    'Wittstock': 'Brandenburg',
    'Vellberg': 'Baden-Württemberg',
    'Bad Vilbel': 'Hessen',
    'Hockenheim': 'Baden-Württemberg',
    'Runkel': 'Hessen',
    'Kelkheim': 'Hessen',
    'Viereth-Trunstadt': 'Bayern',
    'Nellingen': 'Baden-Württemberg',
    'Fürstenfeldbruck': 'Bayern',
    'Glandorf': 'Niedersachsen',
    'Nisterberg': 'Rheinland-Pfalz',
    'Landsberg am Lech': 'Bayern',
    'Bamberg': 'Bayern',
    'Kernen im Remstal': 'Baden-Württemberg',
    'Nottuln': 'Nordrhein-Westfalen',
    'Hechingen': 'Baden-Württemberg',
    'Marktredwitz': 'Bayern',
    'Beilstein': 'Baden-Württemberg',
    'Heusweiler': 'Saarland',
    'Aidlingen': 'Baden-Württemberg',
    'Elze': 'Niedersachsen',
    'Borken': 'Nordrhein-Westfalen',
    'Bernau': 'Brandenburg',
    'Pyrbaum': 'Bayern',
    'Niederstotzingen': 'Baden-Württemberg',
    'Porta Westfalica': 'Nordrhein-Westfalen',
    'Wülfrath': 'Nordrhein-Westfalen',
    'Müllrose': 'Brandenburg',
    'Burg': 'Sachsen-Anhalt',
    'Hüttisheim': 'Baden-Württemberg',
    'Königslutter': 'Niedersachsen',
    'Melsungen': 'Hessen',
    'Bitterfeld-Wolfen': 'Sachsen-Anhalt',
    'Uhldingen-Mühlhofen': 'Baden-Württemberg',
    'Grafenhausen': 'Baden-Württemberg',
    'Freudenstadt': 'Baden-Württemberg',
    'Mengerskirchen': 'Hessen',
    'Heppenheim': 'Hessen',
    'Nürtingen': 'Baden-Württemberg',
    'Rothenburg ob der Tauber': 'Bayern',
    'Sasbach': 'Baden-Württemberg',
    'Malchin': 'Mecklenburg-Vorpommern',
    'Schmölln': 'Thüringen',
    'Lengenfeld': 'Sachsen',
    'Miesbach': 'Bayern',
    'Holzminden': 'Niedersachsen',
    'Gröbenzell': 'Bayern',
    'Mettmann': 'Nordrhein-Westfalen',
    'Eching': 'Bayern',
    'Manching': 'Bayern',
    'Karben': 'Hessen',
    'Mainaschaff': 'Bayern',
    'Baden-Baden': 'Baden-Württemberg',
    'Miltenberg': 'Bayern',
    'Wetter': 'Nordrhein-Westfalen',
    'Garbsen': 'Niedersachsen',
    'Kirchheim bei München': 'Bayern',
    'Prenzlau': 'Brandenburg',
    'Odelzhausen': 'Bayern',
    'Urbach': 'Baden-Württemberg',
    'Schönwald': 'Bayern',
    'Altlandsberg': 'Brandenburg',
    'Hopfen am See': 'Bayern',
    'Schwäbisch Gmünd': 'Baden-Württemberg',
    'Boppard': 'Rheinland-Pfalz',
    'Wertheim': 'Baden-Württemberg',
    'Sindelfingen': 'Baden-Württemberg',
    'Pirmasens': 'Rheinland-Pfalz',
    'Rosbach vor der Höhe': 'Hessen',
    'Neuenrade': 'Nordrhein-Westfalen',
    'Hagenow': 'Mecklenburg-Vorpommern',
    'Kaufbeuren': 'Bayern',
    'Osterhofen': 'Bayern',
    'Rotenburg an der Fulda': 'Hessen',
    'Hofheim am Taunus': 'Hessen',
    'Krumbach': 'Bayern',
    'Bretten': 'Baden-Württemberg',
    'Langenbach': 'Nordrhein-Westfalen',
    'Stadecken-Elsheim': 'Rheinland-Pfalz',
    'Oerlinghausen': 'Nordrhein-Westfalen',
    'Göttingen': 'Niedersachsen',
    'Lampertheim': 'Hessen',
    'Steinau an der Straße': 'Hessen',
    'Wolfhagen': 'Hessen',
    'Plauen': 'Sachsen',
    'Sulzbach': 'Saarland',
    'Herzberg': 'Brandenburg',
    'Biberach': 'Baden-Württemberg',
    'Schmallenberg': 'Nordrhein-Westfalen',
    'Gelsenkirchen': 'Nordrhein-Westfalen',
    'Verden': 'Niedersachsen',
    'Salzgitter': 'Niedersachsen',
    'Furtwangen': 'Baden-Württemberg',
    'Isernhagen': 'Niedersachsen',
    'Schonach im Schwarzwald': 'Baden-Württemberg',
    'Erkelenz': 'Nordrhein-Westfalen',
    'Heide': 'Schleswig-Holstein',
    'Mainbernheim': 'Bayern',
    'Bopfingen': 'Baden-Württemberg',
    'Bremerhaven': 'Bremen',
    'Ampfing': 'Bayern',
    'Hohenberg an der Eger': 'Bayern',
    'Leopoldshöhe': 'Nordrhein-Westfalen',
    'Bergneustadt': 'Nordrhein-Westfalen',
    'Offenbach': 'Hessen',
    'Hennigsdorf': 'Brandenburg',
    'Schliersee': 'Bayern',
    'Gaildorf': 'Baden-Württemberg',
    'Bad Gottleuba-Berggießhübel': 'Sachsen',
    'Kitzingen': 'Bayern',
    'Lennestadt': 'Nordrhein-Westfalen',
    'Weinsberg': 'Baden-Württemberg',
    'Kaiserslautern': 'Rheinland-Pfalz',
    'Plön': 'Schleswig-Holstein',
    'Wittendörp': 'Mecklenburg-Vorpommern',
    'Konz': 'Rheinland-Pfalz',
    'Landau in der Pfalz': 'Rheinland-Pfalz',
    'Nordenham': 'Niedersachsen',
    'Raschau-Markersbach': 'Sachsen',
    'Wirges': 'Rheinland-Pfalz',
    'Lörrach': 'Baden-Württemberg',
    'Öhringen': 'Baden-Württemberg',
    'Zetel': 'Niedersachsen',
    'Weimar': 'Thüringen',
    'Bobingen': 'Bayern',
    'Wemding': 'Bayern',
    'Sankt Augustin': 'Nordrhein-Westfalen',
    'Haselünne': 'Niedersachsen',
    'Maikammer': 'Rheinland-Pfalz',
    'Oberkochen': 'Baden-Württemberg',
    'Siegburg': 'Nordrhein-Westfalen',
    'Greven': 'Nordrhein-Westfalen',
    'Birstein': 'Hessen',
    'Altenburg': 'Thüringen',
    'Brakel': 'Nordrhein-Westfalen',
    'Pinneberg': 'Schleswig-Holstein',
    'Ladenburg': 'Baden-Württemberg',
    'Bad Schwalbach': 'Hessen',
    'Mahlberg': 'Baden-Württemberg',
    'Leverkusen': 'Nordrhein-Westfalen',
    'Mühldorf': 'Bayern',
    'Starnberg': 'Bayern',
    'Meißenheim': 'Baden-Württemberg',
    'Rommerskirchen': 'Nordrhein-Westfalen',
    'Lychen': 'Brandenburg',
    'Zella-Mehlis': 'Thüringen',
    'Lutherstadt Eisleben': 'Sachsen-Anhalt',
    'Eiterfeld': 'Hessen',
    'Neustadt-Glewe': 'Mecklenburg-Vorpommern',
    'Finnentrop': 'Nordrhein-Westfalen',
    'Thalmassing': 'Bayern',
    'Ahrensburg': 'Schleswig-Holstein',
    'Bad Hindelang': 'Bayern',
    'Bad Blankenburg': 'Thüringen',
    'Germersheim': 'Rheinland-Pfalz',
    'Montabaur': 'Rheinland-Pfalz',
    'Bürstadt': 'Hessen',
    'Hasbergen': 'Niedersachsen',
    'Bad Ems': 'Rheinland-Pfalz',
    'Bad Essen': 'Niedersachsen',
    'Norden': 'Niedersachsen',
    'Heiligenhaus': 'Nordrhein-Westfalen',
    'Mutlangen': 'Baden-Württemberg',
    'Edingen-Neckarhausen': 'Baden-Württemberg',
    'Sonneberg': 'Thüringen',
    'Recklinghausen': 'Nordrhein-Westfalen',
    'Delmenhorst': 'Niedersachsen',
    'Freising': 'Bayern',
    'Peine': 'Niedersachsen',
    'Altshausen': 'Baden-Württemberg',
    'Baiersbronn': 'Baden-Württemberg',
    'Lüdenscheid': 'Nordrhein-Westfalen',
    'Alsbach-Hähnlein': 'Hessen',
    'Schenefeld': 'Schleswig-Holstein',
    'Hallbergmoos': 'Bayern',
    'Burbach': 'Nordrhein-Westfalen',
    'Waldkirch': 'Baden-Württemberg',
    'Stuhr': 'Niedersachsen',
    'Bad Wildungen': 'Hessen',
    'Warendorf': 'Nordrhein-Westfalen',
    'Winhöring': 'Bayern',
    'Erlangen': 'Bayern',
    'Pößneck': 'Thüringen',
    'Tengen': 'Baden-Württemberg',
    'Saalfeld': 'Thüringen',
    'Olching': 'Bayern',
    'Berchtesgaden': 'Bayern',
    'Lage': 'Nordrhein-Westfalen',
    'Freigericht': 'Hessen',
    'Bad Friedrichshall': 'Baden-Württemberg',
    'Reichenbach': 'Sachsen',
    'Bruchköbel': 'Hessen',
    'Schwepnitz': 'Sachsen',
    'Quickborn': 'Schleswig-Holstein',
    'Radebeul': 'Sachsen',
    'Korbach': 'Hessen',
    'Landau an der Isar': 'Bayern',
    'Emden': 'Niedersachsen',
    'Eisenbach (Hochschwarzwald)': 'Baden-Württemberg',
    'Hohenstein': 'Thüringen',
    'Duderstadt': 'Niedersachsen',
    'Lindau (Bodensee)': 'Bayern',
    'Bad Hönningen': 'Rheinland-Pfalz',
    'Senftenberg': 'Brandenburg',
    'Günzburg': 'Bayern',
    'Malschwitz': 'Sachsen',
    'Tutzing': 'Bayern',
    'Blankenburg': 'Sachsen-Anhalt',
    'Eschenburg': 'Hessen',
    'Netphen': 'Nordrhein-Westfalen',
    'Apen': 'Niedersachsen',
    'Wittmund': 'Niedersachsen',
    'Jördenstorf': 'Mecklenburg-Vorpommern',
    'Werne': 'Nordrhein-Westfalen',
    'Melle': 'Niedersachsen',
    'Lüneburg': 'Niedersachsen',
    'Bruck': 'Bayern',
    'Wenden': 'Nordrhein-Westfalen',
    'Bad Gandersheim': 'Niedersachsen',
    'Braubach': 'Rheinland-Pfalz',
    'Geldern': 'Nordrhein-Westfalen',
    'Bassum': 'Niedersachsen',
    'Brake': 'Niedersachsen'
}